[package]
name = "prepyrus"
authors = ["Firgrep <code@filipniklas.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
biblatex = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
regex = "1.10.5"
