name: Verify MDX content

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

jobs:
    verification:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache/restore@v4
              id: prepyrus-cache-restore
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('scripts/prepyprus/Cargo.lock') }}-${{ hashFiles('scripts/prepyprus/src/**') }}
            - name: Install Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Install dependencies
              run: cargo build --release --package prepyrus
            - name: Run prepyrus script in verification mode
              run: target/release/prepyrus absolute_bibliography.bib src/pages verify
            - name: Save Prepyrus to cache
              id: prepyrus-cache-save
              uses: actions/cache/save@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('scripts/prepyprus/Cargo.lock') }}-${{ hashFiles('scripts/prepyprus/src/**') }}
