name: Verify MDX content

on:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      - ~/.cargo/bin/
                      - ~/.cargo/registry/index/
                      - ~/.cargo/registry/cache/
                      - ~/.cargo/git/db/
                      - target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('scripts/prepyprus/Cargo.lock') }}-${{ hashFiles('scripts/prepyprus/src/**') }}
            - name: Install Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Install dependencies
              run: cargo build --release --package prepyrus
            - name: Run Rust script
              run: target/release/prepyrus absolute_bibliography.bib src/pages verify
